# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GH_TOKEN}}
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "mschwieger"
  - package-ecosystem: "pip"
    insecure-external-code-execution: allow
    directory: "/"
    registries:
      - github
    schedule:
      interval: "daily"
    reviewers:
      - "mschwieger"
